### ISSUE TITLE
hud is too small on gui 

### ISSUE THREAD

**Issue by emanatetm** [OffKilterMC/InfoHUD#1]
add a way to adjust size please

**Comment by OffKilterMC** [comment]
Thanks for the comment. What UI scale do you run with?

**Comment by emanatetm** [comment]
hi, i use 2x, my resolution is also 1080p
edit: my bad, should've included an image 
![image](https://user-images.githubusercontent.com/88153143/182055812-6ea9bd48-a7f3-4b94-a0ac-e4f7adf3fb6c.png)

**Comment by OffKilterMC** [comment]
Thanks! Would it be OK to use the native size with that gui scale? I currently have it being half the gui text size, which is obviously wrong in that case. Trying to see if I can do a quick fix vs. implementing a new setting in the UI for the short term.

**Comment by emanatetm** [comment]
that works too, thank you

**Comment by OffKilterMC** [comment]
I've just pushed a change which should help this. I will test more and hopefully get out a new version tomorrow.
